"""
Retrieval API.

Run locally:   uvicorn app.api:app --reload
Try it:        http://localhost:8000/docs   (interactive Swagger UI, generated by FastAPI)
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI, Query
from pydantic import BaseModel

from app import config, retrieval


@asynccontextmanager
async def lifespan(app: FastAPI):
    retrieval.pool.open()   # open DB connections once at startup ...
    yield
    retrieval.pool.close()  # ... and close them cleanly at shutdown


app = FastAPI(
    title="Knowledge Retrieval API",
    description="Semantic search over Google Cloud documentation (pgvector + Gemini embeddings).",
    version="0.1.0",
    lifespan=lifespan,
)


class Passage(BaseModel):
    id: int
    source: str
    chunk_index: int
    score: float
    content: str


class SearchResponse(BaseModel):
    query: str
    results: list[Passage]


@app.get("/health")
def health() -> dict:
    with retrieval.pool.connection() as conn:
        count = conn.execute("SELECT count(*) FROM chunks").fetchone()[0]
    return {"status": "ok", "chunks": count}


class Source(BaseModel):
    source: str
    title: str


@app.get("/sources", response_model=list[Source])
def sources() -> list[Source]:
    """The documents in the knowledge base. The first line of chunk 0 is the doc title."""
    sql = """
        SELECT source, split_part(split_part(content, E'\\n', 1), ' > ', 1) AS title
        FROM chunks
        WHERE chunk_index = 0
        ORDER BY title
    """
    with retrieval.pool.connection() as conn:
        rows = conn.execute(sql).fetchall()
    return [Source(source=s, title=t) for s, t in rows]


@app.get("/search", response_model=SearchResponse)
def search(
    q: str = Query(..., min_length=3, description="The question or search text"),
    k: int = Query(5, ge=1, le=20, description="How many passages to return"),
    min_score: float = Query(config.MIN_SCORE, ge=0.0, le=1.0, description="Drop passages below this similarity"),
) -> SearchResponse:
    results = retrieval.search(q, k=k, min_score=min_score)
    return SearchResponse(query=q, results=[Passage(**vars(r)) for r in results])
